name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: facial-auth-system
      REGISTRY: ghcr.io
      USERNAME: ${{ github.actor }}
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t $REGISTRY/${{ github.repository }}:$IMAGE_TAG .

    - name: Push Docker image
      run: |
        docker push $REGISTRY/${{ github.repository }}:$IMAGE_TAG